export const UI = {
  APP_NAME: "JU-AMS",
  APP_LABEL: "JU Activity Hub",
  NAV: {
    MAIN: "Navigation",
    MORE: "More",
    ACCOUNT: "Account",
    SETTINGS: "Settings",
    NOTIFICATIONS: "Notifications",
  },
  CHAT: {
    ONLINE: "Online",
    TITLE: "Activity Chat",
    REPLING_TO: (name: string) => `Replying to ${name}`,
    EDITED: "edited",
    RECORDING: "Recording",
    VOICE_MESSAGE: "Voice message",
    PHOTOS_VIDEOS: "Photos & Videos",
    DOCUMENT: "Document",
    TYPE_MESSAGE: "Type a message...",
    SEARCH_CHATS: "Search or start new chat",
    NO_CHATS: "No chats yet",
    NO_MATCHES: "No matches found.",
    FIRST_MESSAGE: "Send the first message to begin chatting",
    SELECT_ACTIVITY: "Select an activity from the left to start chatting",
    BEGINNING: "Beginning of conversation",
    MEMBERS: (count: number) => `Members (${count})`,
    HOT_THREADS: "Hot threads",
    MOOD_BOOSTERS: "Mood boosters",
    NEW_CONTACT: "New Contact",
    NEW_GROUP: "New Group",
    FILTER_CHATS: "Filter Chats By",
  },
  EMPTY: {
    ACTIVITIES: "No activities yet.",
    APPLICATIONS: "No applications yet.",
    NOTIFICATIONS: "No notifications.",
    RECENT_ACTIVITIES: "No recent activities recorded.",
  },
  FILTER: {
    ALL_CATEGORIES: "All Categories",
    ALL_STATUS: "All Status",
    UNREAD: "Unread",
    FAVORITES: "Favorites",
    CONTACTS: "Contacts",
    NON_CONTACTS: "Non Contacts",
    GROUPS: "Groups",
    DRAFTS: "Drafts",
  },
  TIME: {
    JUST_NOW: "Just now",
    TODAY: "Today",
    YESTERDAY: "Yesterday",
  },
  REPORT: {
    QUARTERLY: "Quarterly Activity Participation Report",
    COORDINATOR: "Coordinator Performance Report",
    SYSTEM_USAGE: "System Usage Trends Report",
    APPLICATIONS_SUMMARY: "Applications Summary Report",
    STUDENTS: "Students Report",
    ATTENDANCE: "Attendance Report",
    FULL_DATASET: "Full Dataset Export",
    NA: "N/A",
    UNKNOWN: "Unknown",
    UNKNOWN_ACTIVITY: "Unknown Activity",
    AVAILABLE: "Available",
    FULL: "FULL",
  },
} as const;
